### ISSUE TITLE
Fix issues with template command

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vegacapsule#130]
We have the following commands:

### Genesis

Cmd: `./vegacapsule template genesis --path net_confs/genesis.tmpl --update-network`

Issue: 

When we have 2 validators and one non validator after above command we have incorrect state like on the image below:

![image](https://user-images.githubusercontent.com/1239637/172278630-b40f8adf-2906-4680-b55e-8469d0a0e664.png)

### Tendermint config:

Cmd: `./vegacapsule template node-sets --type tendermint --path ./net_confs/testdata/tendermint.tmpl  --with-merge --nodeset-mode full --update-network`

When We have the following tendermint:

```
...toml
[rpc]
  cors_allowed_origins = ["*"]
  cors-allowed-methods = ["HEAD", "GET", "POST", ]
  cors-allowed-headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]
...
```

And the template:

```toml
[rpc]
  cors_allowed_origins = ["*"]
  cors-allowed-methods = ["HEAD", "GET", "POST", ]
  cors-allowed-headers = []
```

Then the result is:

```toml
...
[rpc]
  cors-allowed-headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]
...
```

But we expect:

```toml
...
[rpc]
  cors-allowed-headers = []
...
```

### Vega Config

cmd: `./vegacapsule template node-sets --type vega --path ./net_confs/testdata/vega.tmpl --nodeset-mode validator --with-merge`

When We generate network with the following vega config:

```toml
...
[EvtForward]
	Level = "Info"
	RetryRate = "1s"
	{{if .FaucetPublicKey}}
	BlockchainQueueAllowlist = ["{{ .FaucetPublicKey }}"]
	{{end}}
...
```

Then when we update it with the following config:

```toml
...
[EvtForward]
	Level = "Info"
	RetryRate = "1s"
...
```

this is the result:
![image](https://user-images.githubusercontent.com/1239637/172280098-9a45e581-e798-42a4-8d6c-3de14054827a.png)
